name: Publish to npm

# Workflow for publishing to npm when a new major/minor version tag is pushed
# Required secrets:
# - NPM_TOKEN: Token for publishing to npm registry (configured in GitHub repository secrets)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Acepta todas las versiones semánticas

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
